server:
  port: 8082

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: core-service

  datasource:
    url: jdbc:mysql://localhost:3306/obe_ms?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: rTmaktu@2023#

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
