spring:
  application:
    name: discovery

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false   # usually false for the server itself

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: false

