server:
  port: 9081
  cloud:
    discovery:
      enabled: true
  eureka:
    client:
     service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: obe-auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/obe_auth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ??@@suhad@@??

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.MySQL8Dialect   # ✅ updated for Hibernate 6

  jackson:
    mapper:
      default-view-inclusion: true

  mail:
    host: smtp.gmail.com
    port: 587   # ✅ correct Gmail SMTP port
    username: obe.shohaib@gmail.com
    password: shohaib
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

feign:
  hystrix:
    enabled: true

auth:
  token:
    secret: github-secret
